from smartscan.classification.classifier import FileClassifier
from smartscan.classification.few_shot import few_shot_classification
from smartscan.classification.types import ClassificationInput, ClassificationResult, ClassPrototype